### ISSUE TITLE
[Feature Request] Ability to export all colors at once in at least one format

### ISSUE THREAD

**Issue by rlabrecque** [hamvocke/root-loops#1]
I enjoyed creating my [color scheme](https://rootloops.sh?sugar=8&colors=8&sogginess=5&flavor=1&fruit=9&milk=1) with root loops; but after doing so I realized that I have to do the work to manually recreate these in my various tools by copying one color at a time which left me with some dread. What I'd love is to be able to export to a couple different common formats for things like VSCode, or Windows Terminal.

**Comment by hamvocke** [comment]
Thanks, @rlabrecque!

An export function is indeed the thing that's top of mind for me. I'm planning to add an export button that generates the right configuration for your terminal emulator of choice.

Adding export functionality for syntax highlighting, code editors, and IDEs will be a little more tricky, since syntax highlighting schemes often don't follow the simple [ANSI standard](https://en.wikipedia.org/wiki/ANSI_escape_code) used for terminal emulators, but instead often use TextMate's theme language. Not impossible to solve, but it'll take a little more time.

I expect to add different export formats over time, starting with the most popular terminal emulators. I'll keep you posted!

**Comment by cdhunt** [comment]
I would be happy with a simple JSON list to clipboard button so I don't have to click each individual color. I'm probably never going to copy and paste just one.

**Comment by hamvocke** [comment]
I like @cdhunt's idea of having a generic JSON export. I think that can be a solid starting point while I'm working on better support for common terminals -- and syntax highlighters after that.

I just published a first version of a simple JSON export. Maybe that makes things a little easier for now. I'll continue working on this, but wanted to give everyone a heads up that this little button here is now a thing.

![Screenshot from 2024-06-28 19-50-00](https://github.com/hamvocke/root-loops/assets/491469/ba1189e8-4546-4545-a809-c9cc3eb206ad)

**Comment by hamvocke** [comment]
I've iterated on this some more and added an export section to the bottom of the page. I'm looking to grow the exportable formats over time. As of today we've got:

* JSON
* Windows Terminal
* Alacritty
* XResources (for xterm and others)

![export section on root loops](https://github.com/user-attachments/assets/498dfdb7-73bd-4ec9-80c0-5fa08486e1d9)


I'm going to close this issue as resolved. I know there's more work to do. Let's track that work separately, if you miss support for your favorite terminal/editor/CLI tool, don't hesitate to open a new issue and let me know that there's demand :)
