### ISSUE TITLE
Background and color0 are the same color

### ISSUE THREAD

**Issue by crshrprt** [hamvocke/root-loops#8]
First of all thank you for this amazing project, I had a lot of fun creating color themes with root-loops.

I see the **background** color and **color0** are using the same color, but in this way we basically lose an additional color, **color0**, that can be useful for additional background elements (especially in dark themes).

This is an example of what my tmux status bar looks like with a **root-loops** generated color scheme:

![root-loops](https://github.com/user-attachments/assets/6b629ca5-4dcc-47fa-a7c7-e54dd6558ac5)

and this is what it looks like with a self made color scheme, using **color0** with a different color from the background's one:

![opencolor](https://github.com/user-attachments/assets/a6d4ec80-0c9c-4242-adbf-b359267c604b)

**Comment by hamvocke** [comment]
You're raising a good point, and I've been going back and forth on this issue myself.

Right now, Root Loops generates exactly 16 colors. That's a nod to the original 3-bit color palettes used throughout computing. 16 colors was all you could display, and most terminal emulators today kinda stick to that format. But you're right, from today's perspective that limitation is really just *kind of* true. All modern computers can display more than 16 colors. And all modern terminal emulators that I'm aware of support setting background and foreground colors independently from your 16 ANSI colors, leaving you the option to display more than those 16 shades.

I'm happy to support 18 colors for exported color schemes. In fact we'll need more than those 16 ANSI colors for some editor theme exports (think vim/neovim or VS code) anyways for them to look good and it's really not hard to generate more shades of gray while we're at it.

My only question is: what'd you expect from `background` and `foreground` colors? Should `background` always be that darkest "gray" shade and `foreground` be the brightest? In other words should the order from darkest to brightest be:

* `background`
* `color0` (black)
* `color8` (bright black)
* `color7` (white)
* `color15` (bright white)
* `foreground`

?

**Comment by crshrprt** [comment]
Thanks for you prompt response.

What I personally use, based on what I see in most color schemes and applications for terminals I use (with the usual exceptions) is this order (form darkest to brightest):

- `background`
- `color0`
- `color8`
- `color7`
- `foreground`
- `color15`

I've seen some rare cases in color schemes where `color0` was darker than the `background`, but once 18 colors are generated it's easy to swap these two if one wants to.

**Comment by hamvocke** [comment]
Alright, I think this should do the trick. I just introduced two new `foreground` and `background` hues that we use to determine the respective foreground and background colors in all theme exports. The foreground and background colors also show up in the 'cereal bowl', i.e. the display of root loops colors, so that people can copy them manually if they want to.

This introduces a breaking change as it alters the default lightness of the 'white' and 'black' colors, which means people will get slightly different results when they try to regenerate "their" color scheme based on previous recipes. But I think this is a change for the better, as it allows us to create color schemes with more nuanced shading.

Let me know if I got anything wrong here. A lot of places needed tweaking, so chances are I messed something up on the way.

**Comment by crshrprt** [comment]
Thank you, it works great!

I think there's a problem with the `colortest` Terminal Preview:
- bright black row (`1;30m`) is using same color as black 
- bright white row (`1;37m`) is same color as white

Here is root loops's `colortest` Terminal Preview:
![root-loops](https://github.com/user-attachments/assets/132eabbd-02a6-4c7e-8fb9-8e9c6adef34b)

Here is how it looks on a real terminal:
![actual-terminal](https://github.com/user-attachments/assets/50273e43-388e-443e-82f2-16eb3aeac471)

**Comment by hamvocke** [comment]
Ah, great catch.

I'll need to investigate this one separately. It comes down to how different terminals handle 'bright' colors. Some use colors 8-15, others use colors 0-7 and use 'bold' fonts for rendering. The 'colortest' preview I'm using is fairly primitive and uses the 'bold' variant instead of tapping into the bright colors. I should be able to fix that :)
